// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAd3fxFJbqbbwhkTnD6w6RXZx9TjuoLlZs',
    appId: '1:983544332589:web:your_web_app_id',
    messagingSenderId: '983544332589',
    projectId: 'ad4x4-afed6',
    authDomain: 'ad4x4-afed6.firebaseapp.com',
    storageBucket: 'ad4x4-afed6.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAd3fxFJbqbbwhkTnD6w6RXZx9TjuoLlZs',
    appId: '1:983544332589:android:14e5500e7d5428747653a4',
    messagingSenderId: '983544332589',
    projectId: 'ad4x4-afed6',
    storageBucket: 'ad4x4-afed6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA6QfhCWY0qoOE3tkOy4ZDwKTOaFkMXe8Y',
    appId: '1:983544332589:ios:356f20c09af14ee67653a4',
    messagingSenderId: '983544332589',
    projectId: 'ad4x4-afed6',
    storageBucket: 'ad4x4-afed6.firebasestorage.app',
    iosBundleId: 'com.ad4x4.ad4x4Mobile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA6QfhCWY0qoOE3tkOy4ZDwKTOaFkMXe8Y',
    appId: '1:983544332589:ios:356f20c09af14ee67653a4',
    messagingSenderId: '983544332589',
    projectId: 'ad4x4-afed6',
    storageBucket: 'ad4x4-afed6.firebasestorage.app',
    iosBundleId: 'com.ad4x4.ad4x4Mobile',
  );
}
